### ISSUE TITLE
Consider using actions/upload and download artifact actions

### ISSUE THREAD

**Issue by steveoh** [agrc/firebase-website-deploy-composite-action#84]
This best practice seems like something we can apply to this action to increase our security posture.

```yml
- name: ⬆️ Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
          retention-days: 1
```

```yml
 - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist
```
